### ISSUE TITLE
crashes

### ISSUE THREAD

**Issue by jprocket45** [SirWindfield/vanilla-tools#1]
Sadly 1.11.2 crashes right away 1.10.2 I couldn't test either I can move in the world but after a few it crashes this is with no other mods installed and I tried it with Tinkers installed same issue.    https://pastebin.com/Hdw4N44c       I should of filed it here first sorry about the double file won't happen again!

**Comment by mainrs** [comment]
Ye, released 1.0.1. That should fix it "theoretically" :smile: couldn't try it out though
Game is still starting :smile:
**Edit:** Looks like I am doing something wrong. Not sure but I think the mod jars need to get obfuscated to map to minecrafts method names. Will take a look tomorrow 👍

**Comment by mainrs** [comment]
It's super strange because running it in the IDE turns out to be fine. But putting it into a clean instance (mods folder) doesn't work...

**Comment by jprocket45** [comment]
Im not sure to be honest I played for like 5 min then it crashed again on the updated version ill see if anybody can take a look at it that I know deals with mods as well really odd id say.

**Comment by mainrs** [comment]
Looks like it doesn't reobfuscate my function calls to minecraft.

**Comment by mainrs** [comment]
@jprocket45 Would you mind testing the new alpha build 1.0.3? I think I fixed it. Currently in university, will be able to test it in about 6 hours.

**Comment by mainrs** [comment]
@jprocket45 I fixed it for `1.10.2`! Need to take a look at `1.11.2` now. The working version for `1.10.2` is `1.0.3`, released as alpha.

**Comment by jprocket45** [comment]
sorry just got home cool ill check it out in just a few.

**Comment by mainrs** [comment]
No problem. Currently trying to get it work on `1.11.2`.

**Comment by jprocket45** [comment]
I can confirm working on 1.10.2 seems to be no crashes as of the moment gonna try it in a pack this mod could become a big thing I think there are plenty of people out there looking for a new Iguanas

**Comment by mainrs** [comment]
@SlimeKnight has created a mod called [HarvestTweaks](https://github.com/SlimeKnights/HarvestTweaks) which can be used to tinker with the harvest levels of specific ores/blocks.

**Comment by mainrs** [comment]
@jprocket45 A version for both `1.10.2` and `1.11.2` is out!
