### ISSUE TITLE
[1.12] NoClassDefFoundError

### ISSUE THREAD

**Issue by Jomik** [SirWindfield/vanilla-tools#10]
Works fine in client, moved it to a dedicated server installation, crashes before the server even gets up and running.
Should be sufficient information here:

[crash-2017-11-28_12.12.22-server.txt](https://github.com/SirWindfield/vanilla-tools/files/1509613/crash-2017-11-28_12.12.22-server.txt)

**Comment by Jomik** [comment]
Realize that this may be fixed on master, can you please release a version onto curseforge that fixes this? 👍

**Comment by fangedhex** [comment]
yeah I fixed it but not upload it yet to CurseForge.

About the error, it caused by Forge API that removed the Tooltip event from the server, so it was a quick fix !

But thanks anyway to notice it :D
