### ISSUE TITLE
1.12 is trying to use getTrueSource() method that doesn't exist ?

### ISSUE THREAD

**Issue by fangedhex** [SirWindfield/vanilla-tools#9]

**Comment by mainrs** [comment]
Any log/crash log with some more informations? maybe how to reproduce it?

**Comment by mainrs** [comment]
@Fanged-Hex Looks like MC renamed the method within `DamageSource` to `getSourceOfDamage()`. This should work instead of using `getTrueSource()`. Mind trying it out?

**Comment by fangedhex** [comment]
It's a bug that happen in "my" bundled all mc branch :( but on other branches, I have no problem at all ...
